### ISSUE TITLE
Merriweather is not loaded.

### ISSUE THREAD

**Issue by duleise** [hbpasti/heather-hugo#10]
I found this line in `/layouts/partials/head.html`
`<link href='//fonts.googleapis.com/css?family=Merriweather:400,700' rel='stylesheet' type='text/css'>`

I also tried to add `https` in front of the url, or remove `400,700`.
Is there any other place I can check to make sure the font is loaded.
Thank you.

**Comment by hbpasti** [comment]
Sorry, but I couldn't reproduce your issue here. All my browser loaded the font from Google Fonts normally. Have you checked the [Google Fonts Troubleshooting page](https://developers.google.com/fonts/docs/troubleshooting)?

BTW, Adding the `https` might be a better practice nowadays anyway.
